
[gui]
	#The theme to use for the GUI
	#Allowed Values: NORMAL, LIGHT, MIX, DARK
	theme = "DARK"
	#The style of the title
	#Allowed Values: HIDDEN, NORMAL, DETACHED
	title_style = "DETACHED"

[tests]
	#Test for Window Manager.
	#This makes it possible to spawn movable windows on your screen (inside Minecraft ofc)
	window_manager = false

